apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      tier: frontend
  template:
    metadata:
      labels:
        app: django
        tier: frontend
    spec:
      containers:
      - name: contenedor-django
        image: mmarnun/django:v2
        env:
          - name: USUARIO_BD
            valueFrom:
              configMapKeyRef:
                name: django-datos
                key: mysql_user
          - name: CONTRASENA_BD
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: mysql_password
          - name: HOST_BD
            value: mariadb
          - name: NOMBRE_BD
            valueFrom:
              configMapKeyRef:
                name: django-datos
                key: mysql_database
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: django_password                
          - name: DJANGO_SUPERUSER_USERNAME
            valueFrom:
              configMapKeyRef:
                name: django-datos
                key: django_user  
          - name: DJANGO_SUPERUSER_EMAIL
            valueFrom:
              configMapKeyRef:
                name: django-datos
                key: django_email        
          - name: ALLOWED_HOSTS
            value: "*"                                                      
        ports:
          - name: http-server
            containerPort: 8000
